#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PK E2E v2 — single-company extraction test with QA layers L1-L5.

Layout rules (verified NML 2023 + ABOT 2023):
- Audited statement: uppercase TOTAL ASSETS / TOTAL EQUITY AND LIABILITIES,
  note column (small int) + current year FIRST + prior year right.
  Units: thousands PKR.
- 6-year summary table (directors' report): current FIRST, often MILLIONS.
- MD&A analysis sections interleave % columns -> must be page-scoped out.

Parser A (primary):  pdftotext -layout, page-scoped, line regex.
Parser B (secondary): pdfplumber extract_words on the same pages.
QA: L1 identities | L2 cross-year overlap | L2.5 summary-vs-audited scale
check | L3 YoY | L4 opendoors sample | L5 A-vs-B agreement (all fields).
"""
import json
import re
import subprocess
import sys
import time
from pathlib import Path

import pdfplumber

ROOT = Path("/home/ubuntu/research/dlap-tse")
OUT = ROOT / "data_pk"
TMP = Path("/tmp/pk_e2e")
API = "https://financials.psx.com.pk/annQtrStmts.php"
PDF_URL = "https://financials.psx.com.pk/lib/DownloadPDF.php?id={}"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

BS_PAT = re.compile(r"Statement of Financial Position|Balance Sheet", re.I)
PL_PAT = re.compile(r"Statement of Profit or Loss|Statement of Profit and Loss|Profit or Loss Account|Profit and Loss Account", re.I)

FIELDS = [
    ("revenue", [r"^Net sales(?: including.*)?$", r"^Sales - net$", r"^Sales \u2013 net$", r"^Sales\(net\)$", r"^Sales(?: \(net\))?$", r"^Gross sales$", r"^R?REVENUE$", r"^Net revenue$"]),
    ("cost_of_sales", [r"^Cost of (?:goods |sales )?sales$", r"^Cost of goods sold$", r"^Cost of revenue$"]),
    ("gross_profit", [r"^Gross (?:profit|loss)$"]),
    ("net_income", [r"^Profit after taxation$", r"^Profit after tax$", r"^Profit for the year$", r"^Net profit$", r"^Loss after taxation$", r"^Loss for the year$"]),
    ("dividends", [r"^Ordinary cash dividends$", r"^Cash dividends$", r"^Dividends$"]),
    ("total_assets", [r"^TOTAL ASSETS$", r"^Total assets$"]),
    ("total_equity", [r"^TOTAL EQUITY$", r"^Total equity$", r"^TOTAL CAPITAL AND RESERVES$"]),
    ("total_liabilities", [r"^TOTAL LIABILITIES$", r"^Total liabilities$"]),
    ("current_assets", [r"^TOTAL CURRENT ASSETS$", r"^Total current assets$", r"^Current assets$"]),
    ("current_liabilities", [r"^TOTAL CURRENT LIABILITIES$", r"^Total current liabilities$", r"^Current liabilities$"]),
    ("cash", [r"^Cash and (?:cash )?equivalents$", r"^Cash and bank balances$", r"^Cash and bank$"]),
    ("inventory", [r"^Inventories$", r"^Stock-in-trade$"]),
    ("ppe", [r"^Property, plant and equipment$", r"^Property and equipment$",
             r"^Operating fixed assets$", r"^Fixed assets(?: - net)?$", r"^Fixed assets$"]),
    ("cfo", [r"^Net cash generated from operating activities$", r"^Net cash (?:from|generated by) operating activities$", r"^Operating activities$", r"^Net cash \(outflow\) / inflow from operating activities$", r"^Net cash used in operating activities$"]),
]
BS_FIELDS = [f[0] for f in FIELDS if f[0] in (
    "total_assets", "total_equity", "total_liabilities", "current_assets",
    "current_liabilities", "cash", "inventory", "dividends", "ppe")]
PL_FIELDS = [f[0] for f in FIELDS if f[0] in (
    "revenue", "cost_of_sales", "gross_profit", "net_income", "cfo")]
TOL = 0.01


def clean_num(s):
    if s is None:
        return None
    s = str(s).strip().replace(",", "")
    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]
    if not re.match(r"^-?\d+(\.\d+)?$", s):
        return None
    try:
        return float(s)
    except ValueError:
        return None


def line_values(line):
    """Token-based: label = non-numeric tokens, nums = numeric tokens in
    order. Handles single-space-separated values (pdftotext collapses
    narrow columns to one space), tab-separated lines, and paren negatives."""
    toks = line.strip().split()
    if not toks:
        return None, []
    label_parts, nums = [], []
    for t in toks:
        n = clean_num(t)
        if n is not None:
            nums.append(n)
        else:
            label_parts.append(t)
    return " ".join(label_parts).rstrip("* "), nums


def cur_prior(nums):
    big = [n for n in nums if abs(n) >= 1000]
    cur = big[0] if big else (nums[0] if nums else None)
    prior = big[1] if len(big) >= 2 else None
    return cur, prior


def parse_page_text(page_text, want):
    out = {}
    for line in page_text.splitlines():
        label, nums = line_values(line)
        if not label or not nums:
            continue
        label = label.rstrip("* ")
        for name in want:
            if name in out:
                continue
            for p in dict(FIELDS)[name]:
                if re.match(p, label, re.I):
                    cur, prior = cur_prior(nums)
                    if cur is not None:
                        out[name] = (cur, prior, line.strip()[:130])
                    break
    return out


def api_reports(symbol):
    r = subprocess.run(["curl", "-sL", "--max-time", "60", "-H", f"User-Agent: {UA}",
                        "-d", f"name=get_comp_data&smbCode={symbol}", API],
                       capture_output=True)
    recs = json.loads(r.stdout.decode("utf-8", errors="ignore"))
    ann = []
    for rec in recs:
        m = re.search(r"DownloadPDF\.php\?id=([^\"']+)", rec.get("Reports", ""))
        if not m:
            continue
        label = re.sub(r"<[^>]+>", "", rec.get("Reports", ""))
        if "annual" not in label.lower():
            continue
        ym = re.search(r"(20\d{2})", rec.get("period_ended", ""))
        ann.append({"id": m.group(1), "year": int(ym.group(1)) if ym else None,
                    "period": rec.get("period_ended", "")})
    ann.sort(key=lambda x: x["year"] or 0)
    return ann


def find_statement_pages(pages):
    """-> (summary_idx, audited_bs_idx, pl_idx, cfs_idx).
    Audited page = UPPERCASE 'TOTAL EQUITY AND LIABILITIES' (audited
    statements use uppercase totals; summary/analysis tables use title
    case). Fallbacks for old-style statements ('Balance Sheet' heading,
    2-page spreads, no uppercase totals): first candidate carrying the
    'SHARE CAPITAL AND RESERVES' / 'EQUITY AND LIABILITIES' section
    marker, else the first candidate. Vertical/Horizontal-analysis pages
    (percentage tables) are always excluded."""
    CONTENT = re.compile(r"total assets|total equity and liabilities|total liabilities", re.I)
    TE_UPPER = re.compile(r"TOTAL EQUITY AND LIABILITIES")
    # audited statements carry a thousands-units header; horizontal-analysis
    # tables say "(Rs. Million)" — use it to discriminate
    UNITS_K = re.compile(r"(Rupees?|PKR|Rs\.?)\s*(in\s+)?['\u2018\u2019]?0*000|Rupees? in thousand", re.I)
    # statement-start marker: standalone uppercase section heading line
    BS_START = re.compile(r"^\s*SHARE CAPITAL AND RESERVES\s*$|^\s*EQUITY AND LIABILITIES\s*$", re.M)
    ANALYSIS = re.compile(r"Vertical Analysis|Horizontal Analysis|Analysis of Financial|AT A GLANCE", re.I)
    PL_CONTENT = re.compile(r"net sales|profit after|cost of sales|cost of goods sold|gross profit", re.I)
    CFS_PAT = re.compile(r"Statement of Cash Flows|Cash Flow Statement", re.I)
    CFS_CONTENT = re.compile(r"net cash|dividends? paid", re.I)
    cands, sum_idx = [], None
    for i, p in enumerate(pages):
        if ANALYSIS.search(p):
            continue
        if CONTENT.search(p) or BS_START.search(p) or TE_UPPER.search(p):
            cands.append(i)
            if sum_idx is None:
                sum_idx = i
    aud_idx = None
    for i in cands:
        if TE_UPPER.search(pages[i]) and UNITS_K.search(pages[i]):
            aud_idx = i
            break
    if aud_idx is None:
        for i in cands:
            if TE_UPPER.search(pages[i]) and BS_START.search(pages[i]):
                aud_idx = i
                break
    if aud_idx is None:
        for i in cands:
            if TE_UPPER.search(pages[i]):
                aud_idx = i
                break
    if aud_idx is None:
        for i in cands:
            if BS_START.search(pages[i]):
                aud_idx = i
                break
    if aud_idx is None and cands:
        aud_idx = cands[0]
    pl_idx = None
    start = aud_idx if aud_idx is not None else 0
    for i in range(start, len(pages)):
        if ANALYSIS.search(pages[i]):
            continue
        if PL_PAT.search(pages[i]) or PL_CONTENT.search(pages[i]):
            pl_idx = i
            break
    cfs_idx = None
    for i in range((pl_idx if pl_idx is not None else start) + 1, len(pages)):
        if CFS_PAT.search(pages[i]) and CFS_CONTENT.search(pages[i]):
            cfs_idx = i
            break
    return sum_idx, aud_idx, pl_idx, cfs_idx


def cluster_reps(xs, gap):
    clusters = []
    for x in sorted(xs):
        if not clusters or x - clusters[-1][-1] > gap:
            clusters.append([x])
        else:
            clusters[-1].append(x)
    return [(sum(c) / len(c), len(c)) for c in clusters]


def x_parse_page(pdf, page_idx):
    """Generic x-aligned page parser. Values may be RIGHT-aligned (cluster
    by x1) or CENTERED (cluster by midpoint) — try both, keep the
    representation with more well-populated columns. cur_x = rep nearest
    the max-year header x0 (fallback: leftmost). Returns
    {field: (cur, prior, label)}."""
    out = {}
    words = pdf.pages[page_idx].extract_words(x_tolerance=2)
    lines = {}
    big = []  # (x0, x1) of big numbers
    for w in words:
        top = round(w["top"] / 3) * 3
        lines.setdefault(top, []).append((w["x0"], w["x1"], w["text"]))
        n = clean_num(w["text"])
        if n is not None and abs(n) >= 1000 and not (1990 <= n <= 2035):
            big.append((w["x0"], w["x1"]))
    if len(big) < 2:
        return out
    # dual clustering: x1 for right-aligned, midpoint for centered tables
    cands = []
    for key, gap in ((lambda t: t[1], 15), (lambda t: (t[0] + t[1]) / 2, 15)):
        reps = cluster_reps([key(t) for t in big], gap)
        score = sum(1 for _, c in reps if c >= 4)
        cands.append((score, reps, key))
    best = max(cands, key=lambda c: c[0])
    reps, key = best[1], best[2]
    hdr_x = None
    for top in sorted(lines):
        yrs = [(int(t), x0) for x0, x1, t in lines[top] if re.fullmatch(r"20\d{2}", t)]
        if len(yrs) >= 2:
            hdr_x = max(yrs)[1]  # x0 of the LARGEST year (not max x0!)
            break
    if hdr_x is not None:
        cur = min(reps, key=lambda r: abs(r[0] - hdr_x))
        cur_x = cur[0] if abs(cur[0] - hdr_x) <= 120 else None
    else:
        cur_x = None
    if cur_x is None:
        cur_x = min(r[0] for r in reps)  # leftmost = current year
    right = [r[0] for r in reps if r[0] > cur_x + 15]
    prior_x = min(right) if right else cur_x
    for top in sorted(lines):
        toks = sorted(lines[top])
        nums = [(key((x0, x1)), clean_num(t)) for x0, x1, t in toks if clean_num(t) is not None]
        if not nums:
            continue
        label = " ".join(t for x0, x1, t in toks if clean_num(t) is None).rstrip("* ")
        if not label or len(label) > 70:
            continue
        for name in [f[0] for f in FIELDS]:
            if name in out:
                continue
            for p in dict(FIELDS)[name]:
                if re.match(p, label, re.I):
                    def pick(x_target, xs):
                        best = min(xs, key=lambda x: abs(x - x_target))
                        return dict(zip(xs, [n for _, n in nums]))[best] if abs(best - x_target) < 60 else None
                    xs = [x for x, _ in nums]
                    cur = pick(cur_x, xs)
                    prior = pick(prior_x, xs)
                    if cur is not None:
                        out[name] = (cur, prior, label)
                    break
    return out


def parse_summary_aligned(path, sum_idx):
    with pdfplumber.open(path) as pdf:
        if sum_idx >= len(pdf.pages):
            return {}
        return x_parse_page(pdf, sum_idx)


def secondary_parse(path, page_idx):
    with pdfplumber.open(path) as pdf:
        if page_idx >= len(pdf.pages):
            return {}
        return {k: v[0] for k, v in x_parse_page(pdf, page_idx).items()}


def section_sum(pages, aud_idx, heading_pat):
    """Fallback for unlabeled section subtotals (NML style): sum item lines
    between a section heading and the next section boundary. Skips bare
    subtotal lines (label empty) to avoid double counting; uses the last
    bare subtotal if no items were found. Section boundaries (with or
    without numbers): Total/TOTAL (Non-Current/Current) Assets/Liabilities/
    Equity, CONTINGENCIES, SHARE CAPITAL, all-caps headings."""
    STOP = re.compile(r"^(TOTAL|Total) (Non-Current|Current )?(Assets|Liabilities|Equity)"
                      r"|^CONTINGENCIES|^SHARE CAPITAL|^AUTHORISED|^ISSUED", re.I)
    for pg in range(max(0, aud_idx - 1), min(len(pages), aud_idx + 3)):
        started, found = False, False
        total, last_bare = 0.0, None
        for line in pages[pg].splitlines():
            label, nums = line_values(line)
            if not started:
                if label and re.match(heading_pat, label, re.I):
                    started = True
                continue
            if label and (STOP.match(label) or (not nums and label.isupper())):
                if found:
                    return total
                if last_bare is not None:
                    return last_bare
                return None
            if not nums:
                continue
            if not label:
                cur, _ = cur_prior(nums)
                if cur is not None:
                    last_bare = cur
                continue
            cur, _ = cur_prior(nums)
            if cur is not None:
                total += cur
                found = True
        if found:
            return total
    return None


def extract_pdf(path):
    """-> (fields, summary, pages4, scanned). Primary: pdftotext page-scoped."""
    r = subprocess.run(["pdftotext", "-layout", str(path), "-"],
                       capture_output=True, timeout=180)
    text = r.stdout.decode("utf-8", errors="ignore")
    if len(text.strip()) < 200:
        return {}, {}, (None, None, None, None), True
    pages = text.split("\f")
    sum_idx, aud_idx, pl_idx, cfs_idx = find_statement_pages(pages)

    fields = {}
    if aud_idx is not None:
        lo, hi = max(0, aud_idx - 1), min(len(pages), aud_idx + 2)
        for pg in range(lo, hi):
            for k, v in parse_page_text(pages[pg], BS_FIELDS).items():
                fields.setdefault(k, {"cur": v[0], "prior": v[1], "ev": v[2], "src": "aud"})
        # unlabeled section subtotals (NML style): CURRENT ASSETS / LIABILITIES
        if "current_assets" not in fields and aud_idx is not None:
            s = section_sum(pages, aud_idx, r"^Current Assets$")
            if s is not None:
                fields["current_assets"] = {"cur": s, "prior": None, "ev": "section sum", "src": "sum"}
        if "current_liabilities" not in fields and aud_idx is not None:
            s = section_sum(pages, aud_idx, r"^Current Liabilities$")
            if s is not None:
                fields["current_liabilities"] = {"cur": s, "prior": None, "ev": "section sum", "src": "sum"}
    if pl_idx is not None:
        for pg in range(pl_idx, min(pl_idx + 2, len(pages))):
            for k, v in parse_page_text(pages[pg], PL_FIELDS).items():
                fields.setdefault(k, {"cur": v[0], "prior": v[1], "ev": v[2], "src": "pl"})
    if cfs_idx is not None:
        for pg in range(cfs_idx, min(cfs_idx + 2, len(pages))):
            for k, v in parse_page_text(pages[pg], ("cfo",)).items():
                fields.setdefault(k, {"cur": v[0], "prior": v[1], "ev": v[2], "src": "cfs"})
    # summary (cross-check anchor, units may differ) — x-aligned parsing
    summary = {}
    if sum_idx is not None and sum_idx != aud_idx:
        summary = parse_summary_aligned(path, sum_idx)
    return fields, summary, (sum_idx, aud_idx, pl_idx, cfs_idx), False


# ------------------------------------------------------------ QA layers ---
def approx(a, b, tol=TOL):
    if a is None or b is None:
        return None
    if abs(b) < 1:
        return None
    return abs(a - b) / abs(b) <= tol


def run_l1(rows):
    fl = []
    for y, f in rows.items():
        ta, tl, eq = f.get("total_assets"), f.get("total_liabilities"), f.get("total_equity")
        if ta and tl and eq and approx(ta, tl + eq) is False:
            fl.append((y, "L1:TA!=TL+Eq", ta, tl + eq))
        sale, cgs, gp = f.get("revenue"), f.get("cost_of_sales"), f.get("gross_profit")
        if sale and cgs and gp and approx(sale - abs(cgs), gp) is False:
            fl.append((y, "L1:Sales-COGS!=GP", sale - abs(cgs), gp))
    return fl


def run_l2(rows):
    fl = []
    yrs = sorted(rows)
    for i in range(1, len(yrs)):
        yp, yc = yrs[i - 1], yrs[i]
        for fld in ("total_assets", "total_liabilities", "total_equity",
                    "revenue", "net_income", "cash"):
            a = rows[yp].get(fld)
            b = rows[yc].get(fld + "_p")
            if a is not None and b is not None and approx(a, b) is False:
                fl.append((yc, f"L2:{fld} overlap", a, b))
    return fl


def run_l25(rows):
    """Summary table (units vary: millions/thousands) vs audited (thousands)."""
    fl = []
    for y, f in rows.items():
        for fld in ("total_assets", "total_equity", "total_liabilities", "revenue", "net_income"):
            s = f.get(fld + "_sum")
            a = f.get(fld)
            if s is None or a is None:
                continue
            ok = approx(a, s) or approx(a, s * 1000) or approx(a * 1000, s)
            if not ok:
                fl.append((y, f"L2.5:{fld} summary-vs-audited", a, s))
    return fl


def scale_agnostic(a, b):
    """Equal up to a power-of-1000 scale (unit normalization)."""
    if a is None or b is None or a == 0 or b == 0:
        return False
    r = a / b
    return (0.995 < r < 1.005) or (995 < r < 1005) or (0.000995 < r < 0.001005)


def run_l5(rows, ann, wd):
    """Parser B (pdfplumber words) vs parser A on the SAME audited page."""
    agree = total = 0
    l5flags = []
    for rec in ann:
        y = rec["year"]
        f = rows.get(y)
        if not f:
            continue
        path = wd / f"{y}.pdf"
        try:
            _, _, (_, ai, _, _), scanned = extract_pdf(path)
            if scanned or ai is None:
                continue
            b = secondary_parse(path, ai)
            for name in [k for k in f if not k.endswith(("_p", "_src", "_ev", "_sum"))]:
                if name not in b:
                    continue
                total += 1
                if scale_agnostic(f[name], b[name]):
                    agree += 1
                else:
                    l5flags.append((y, f"L5:{name} A vs B", f[name], b[name]))
        except Exception as e:
            print(f"    {y}: L5 skip {type(e).__name__}: {e}")
    return agree, total, l5flags


def run_l3(rows):
    fl = []
    yrs = sorted(rows)
    for i in range(1, len(yrs)):
        for fld in ("total_assets", "revenue", "total_equity"):
            a, b = rows[yrs[i - 1]].get(fld), rows[yrs[i]].get(fld)
            if a and b and a > 0 and (b / a > 5 or b / a < 0.2):
                fl.append((yrs[i], f"L3:{fld} YoY x{b/a:.1f}", a, b))
    return fl


def load_opendoors_sample():
    import xml.etree.ElementTree as ET
    import zipfile
    p = Path("/tmp/od_sample.xlsx")
    if not p.exists():
        return {}
    z = zipfile.ZipFile(p)
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    ss = []
    root = ET.fromstring(z.read("xl/sharedStrings.xml"))
    for si in root.findall("m:si", ns):
        ss.append("".join(t.text or "" for t in si.iter("{http://schemas.openxmlformats.org/spreadsheetml/2006/main}t")))
    sheet = [f for f in z.namelist() if f.startswith("xl/worksheets/sheet")][0]
    root = ET.fromstring(z.read(sheet))
    data, hdr = {}, None
    for row in root.iter("{http://schemas.openxmlformats.org/spreadsheetml/2006/main}row"):
        vals = []
        for c in row:
            v = c.find("m:v", ns)
            t = c.get("t")
            vals.append(ss[int(v.text)] if t == "s" and v is not None else (v.text if v is not None else ""))
        if hdr is None:
            hdr = vals
            continue
        rec = dict(zip(hdr, vals))
        try:
            key = (rec.get("symbol", "").strip(), int(rec.get("Year", 0)))
        except (TypeError, ValueError):
            continue
        data[key] = {
            "total_assets": clean_num(rec.get(" Total Assets", "")),
            "current_assets": clean_num(rec.get("Current Assets", "")),
            "current_liabilities": clean_num(rec.get("Current Liabilities", "")),
            "revenue": clean_num(rec.get("Sales", "")),
            "net_income": clean_num(rec.get("Profit after tax ", "")),
        }
    return data


def run_l4(rows, symbol):
    sample = load_opendoors_sample()
    if not sample:
        return [], "opendoors sample NOT found"
    fl, matched = [], 0
    for y, f in rows.items():
        ext = sample.get((symbol, y))
        if not ext:
            continue
        for fld, ev in ext.items():
            if ev is None or f.get(fld) is None:
                continue
            matched += 1
            if approx(f[fld], ev) is False:
                fl.append((y, f"L4:{fld} vs opendoors", f[fld], ev))
    return fl, f"{matched} pairs checked vs opendoors"


def main():
    symbol = sys.argv[1] if len(sys.argv) > 1 else "ABOT"
    wd = TMP / symbol
    wd.mkdir(parents=True, exist_ok=True)

    ann = api_reports(symbol)
    print(f"[1] {symbol}: {len(ann)} annual reports ({ann[0]['year']}-{ann[-1]['year']})")
    for i, rec in enumerate(ann, 1):
        out = wd / f"{rec['year']}.pdf"
        if not out.exists() or out.stat().st_size < 10000:
            subprocess.run(["curl", "-sL", "--max-time", "120", "-H", f"User-Agent: {UA}",
                            "-o", str(out), PDF_URL.format(rec["id"])])
            time.sleep(0.5)

    rows = {}
    for rec in ann:
        path = wd / f"{rec['year']}.pdf"
        try:
            ex, summary, (si, ai, pi, ci), scanned = extract_pdf(path)
        except Exception as e:
            print(f"    {rec['year']}: EXTRACT ERR {type(e).__name__}: {e}")
            continue
        f = {}
        for name, d in ex.items():
            f[name] = d["cur"]
            f[name + "_p"] = d["prior"]
            f[name + "_src"] = d["src"]
            f[name + "_ev"] = d["ev"]
        for name, (cur, _, _) in summary.items():
            f[name + "_sum"] = cur
        if scanned:
            f["_status"] = "SCANNED"
        rows[rec["year"]] = f
        n = sum(1 for k in f if not k.endswith(("_p", "_src", "_ev", "_sum")))
        tag = " SCANNED" if scanned else f" | pages sum={si} aud={ai} pl={pi} cfs={ci}"
        print(f"    {rec['year']}: {n} fields{tag}")

    json.dump({str(k): v for k, v in rows.items()},
              open(OUT / f"p0_e2e_{symbol}_raw.json", "w"), indent=1)

    print("\n[4] QA layers:")
    all_flags = []
    for tag, fn in (("L1 accounting identities", run_l1), ("L2 cross-year overlap", run_l2),
                    ("L2.5 summary-vs-audited", run_l25), ("L3 YoY sanity", run_l3)):
        fl = fn(rows)
        all_flags += fl
        print(f"    {tag}: {len(fl)} flag(s)")
        for f in fl:
            print("      !", f)
    l4f, l4msg = run_l4(rows, symbol)
    all_flags += l4f
    print(f"    L4 external: {l4msg}, {len(l4f)} flag(s)")
    for f in l4f:
        print("      !", f)

    # L5: parser B agreement on ALL extracted fields
    print("\n[5] L5 parser A vs B agreement:")
    agree, total, l5flags = run_l5(rows, ann, wd)
    print(f"    agreement {agree}/{total} = {100*agree/max(total,1):.1f}%")
    for f in l5flags:
        print("      !", f)

    print("\n[6] Extracted panel (audited statement, thousands PKR):")
    hdr = [("year", "year"), ("TA", "total_assets"), ("TL", "total_liabilities"),
           ("Eq", "total_equity"), ("CA", "current_assets"), ("CL", "current_liabilities"),
           ("Sales", "revenue"), ("COGS", "cost_of_sales"), ("GP", "gross_profit"),
           ("PAT", "net_income"), ("Div", "dividends"), ("Cash", "cash"),
           ("Inv", "inventory"), ("CFO", "cfo")]
    print("  " + " | ".join(f"{h[0]:>11}" for h in hdr))
    for y in sorted(rows):
        f = rows[y]
        cells = [str(y)] + [f"{f.get(h[1], ''):,.0f}" if f.get(h[1]) else "" for h in hdr[1:]]
        if f.get("cost_of_sales"):
            i = hdr.index(("COGS", "cost_of_sales"))
            cells[i] = f"{abs(f['cost_of_sales']):,.0f}"
        print("  " + " | ".join(f"{c:>11}" for c in cells))

    print(f"\nDone. raw JSON: data_pk/p0_e2e_{symbol}_raw.json")
    print(f"TOTAL flags: {len(all_flags)}")


if __name__ == "__main__":
    main()
